### PR TITLE
Fix Incorrect Encoding of CES Triples

### LINKED ISSUE #207: Conditional Endorsement Series Triple gets omitted when using cocli tool to create CoMID
When using the example CoMID .json file https://github.com/veraison/corim/blob/f48404b84d34cd52e08fda1d6b826328a668e200/comid/example_test.go#L252 with cocli (https://github.com/[veraison/cocli](https://github.com/veraison/cocli)) to create a CoMID .cbor file, the Conditional Endorsement Series Triple gets omitted from the output.

I've attached the CoMID .json file, which is copied from example_test.go.
Command to generate CoMID: `cocli comid create --template <path_to_comid-test.json>`

[comid-test.json](https://github.com/user-attachments/files/21129480/comid-test.json)

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**
Fixes #207

### CODE REVIEW

File: comid/example_test.go [hunk 1]
```diff
@@ -161,7 +161,7 @@ func Example_encode() {
...
...354845584b74524b6f6436514c634f4c504131513d3d0a2d2d2d2d2d454e44205055424c4943204b45592d2d2d2d2d038182a101d8255031fb5abf023e4992aa4e95f9c1503bfa81d9022a78b12d2d2d2d2d424547494e205055424c4943204b45592d2d2d2d2d0a4d466b77457759484b6f5a497a6a3043415159494b6f5a497a6a304441516344516741455731427671462b2f727938425761375a454d553178595948455138420a6c4c54344d46484f614f2b4943547449767245654570722f7366544150363648326843486462354845584b74524b6f6436514c634f4c504131513d3d0a2d2d2d2d2d454e44205055424c4943204b45592d2d2d2d2d08818282a300a500d86f445502c000016941434d45204c74642e026a526f616452756e6e65720300040101d902264702deadbeefdead02d8255031fb5abf023e4992aa4e95f9c1503bfa81a200d8255031fb5abf023e4992aa4e95f9c1503bfa01aa01d90228020282820644abcdef00820644ffffffff03a201f403f504d9023044010203040544ffffffff064802005e1000000001075020010db8000000000000000000000068086c43303258373056484a484435094702deadbeefdead0a5031fb5abf023e4992aa4e95f9c1503bfaa16656616c756573818281a200d8255031fb5abf023e4992aa4e95f9c1503bfa01a501d90228020282820644abcdef00820644ffffffff03a201f403f504d9023044010203040544ffffffff81a200d8255031fb5abf023e4992aa4e95f9c1503bfa01a3064802005e1000000001075020010db8000000000000000000000068094702deadbeefdead
```
Comment (thomas-fossati) [inline comid/example_test.go:164]: this is not correct: it still produces the spurious `”Values"` key:
```
{
  "Values":[
    [
      [
        {
          0:37(h'31fb5abf023e4992aa4e95f9c1503bfa'),
          1:{
            1:552(2),
            2:[[6, h'abcdef00'], [6, h'ffffffff']],
            3:{1: false, 3: true},
            4:560(h'01020304'),
            5:h'ffffffff'
          }
        }
      ],
      [
        {
          0:37(h'31fb5abf023e4992aa4e95f9c1503bfa'),
          1:{
            6:h'02005e1000000001',
            7:h'20010db8000000000000000000000068',
            9:h'02deadbeefdead'
          }
        }
      ]
    ]
  ]
}
```

Comment (yogeshbdeshpande) [reply comid/example_test.go:164]: > this is not correct: it still produces the spurious `”Values"` key:
> 
> ```
> {
>   "Values":[
>     [
>       [
>         {
>           0:37(h'31fb5abf023e4992aa4e95f9c1503bfa'),
>           1:{
>             1:552(2),
>             2:[[6, h'abcdef00'], [6, h'ffffffff']],
>             3:{1: false, 3: true},
>             4:560(h'01020304'),
>             5:h'ffffffff'
>           }
>         }
>       ],
>       [
>         {
>           0:37(h'31fb5abf023e4992aa4e95f9c1503bfa'),
>           1:{
>             6:h'02005e1000000001',
>             7:h'20010db8000000000000000000000068',
>             9:h'02deadbeefdead'
>           }
>         }
>       ]
>     ]
>   ]
> }
> ```

yes identified the bug, already and working on it!

**Review by thomas-fossati — APPROVED** [review]
